name: CI

on:
  push:
    branches:
  #    - master
      - v4.7.x-dev
  # pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to GitHub Container Registry
        run: echo "${GHCR_TOKEN}" | docker login ghcr.io -u "mistcommunity-bot" --password-stdin

      - name: Build Docker image
        run: |
          docker build --rm -t ghcr.io/${GITHUB_REPOSITORY_OWNER##*/}/tests:${GITHUB_SHA} \
            --build-arg API_VERSION_SHA=${{ github.sha }} \
            --build-arg API_VERSION_NAME=${{ github.ref_name }} .
          docker push ghcr.io/${GITHUB_REPOSITORY_OWNER##*/}/tests:${GITHUB_SHA}

  flake8:
    name: Run Flake8 Tests
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/${{ github.repository_owner }}/tests:${{ github.sha }}
    env:
      GIT_STRATEGY: none
    steps:
      - name: Run Flake8 checks
        run: |
          cd /mist.tests/
          flake8 misttests/integration/api/mistrequests.py
          flake8 misttests/integration/api/utils.py
          flake8 misttests/integration/gui/steps/browser.py
          flake8 misttests/integration/gui/steps/images.py
          flake8 misttests/integration/gui/steps/networks.py
          flake8 misttests/integration/gui/steps/org_context.py
          flake8 misttests/integration/gui/steps/popups.py
          flake8 misttests/integration/gui/steps/scroll.py
          flake8 misttests/integration/gui/steps/setup.py
          flake8 misttests/integration/gui/steps/team.py
